---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pull loadimpact/k6 image.."
      - docker pull loadimpact/k6
  build:
    commands:
      - echo "Run performance tests"
      - docker run -i -v $(pwd):/scripts loadimpact/k6 run /scripts/Cloud_Tests/k6CloudTest_AWS.js
  post_build:
    commands:
      - echo "Performance tests completed successfully!"
