name: K6 Load Test
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v4
      - name: step 2 - install k6
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install -y k6
      - name: step 3 - run k6 load test
        uses: grafana/run-k6-action@v1
        with:
          path: ./Cloud_Tests/k6CloudTest_AWS.js
      - run: ls & mkdir report & mv index.html report/index.html
      - name: step 4 - upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Performance Test Report
          path: report/index.html
      - name: step 5 - publish report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report/index.html